/// defines file
#define MAX_SIMULTANEOUS_GAMES 16
#define LANE_COUNT 5

#define GAME_STATE_PREINIT 0
#define GAME_STATE_PLAYER1 1
#define GAME_STATE_PLAYER2 2
#define GAME_STATE_FINISHED 3

#define PLANE_BOARD_BASE 10
#define PLANE_BOARD_OBJECTS 20
#define PLANE_CARDS 30

